#include "lab1/RawNetworkBuffer.hpp"
#include "lab2/ImageBuffer.hpp"
#include "lab3/DocumentManager.hpp"
#include <iostream>

int main()
{
	std::cout << "*** Start laboratory #1 - The Rule of Three and the shallow copy problem ***\n";
	{
		lab1::RawNetworkBuffer buffer{ 10 };
		
		std::cout << "\nDemonstration of the copy constructor:\n";
		lab1::RawNetworkBuffer buffer_for_copy_constructor{buffer};

		std::cout << "\nDemonstration of the assignment operator:\n";
		lab1::RawNetworkBuffer buffer_for_assignment_oper{5};
		buffer_for_assignment_oper = buffer;

		std::cout << "\nDemonstration of self-assignment:\n";
		buffer_for_assignment_oper = buffer_for_assignment_oper;
		std::cout << "\n";
	}
	std::cout << "*** End laboratory #1 ***\n\n";

	std::cout << "*** Start laboratory #2 - The Rule of Five and the semantics of movement ***\n";
	{
		lab2::ImageBuffer buffer_orig{ 1024 };
		
		std::cout << "--- Copying demonstration ---\n";
		lab2::ImageBuffer buffer_copy{ buffer_orig };
		lab2::ImageBuffer buffer_copy_copy{};
		buffer_copy_copy = buffer_copy;
		
		std::cout << "--- Movement demonstration ---\n";
		lab2::ImageBuffer buffer_move(std::move(buffer_orig));
		buffer_copy = std::move(buffer_move);

		std::cout << "--- Destructor ---\n";
	}
	std::cout << "*** End laboratory #2 ***\n\n";


	std::cout << "*** Start laboratory #3 - Rule of Zero ***\n";
	{
		std::cout << "--- Creating a source document via the user-defined builder ---\n";
		lab3::DocumentManager doc1{ "Report_2026", 100 };
		doc1.print_info();

		std::cout << "--- Creating a deep copy via the standard copy constructor (generated by the compiler) ---\n";
		lab3::DocumentManager doc2{ doc1 };
		doc2.print_info();

		std::cout << "--- Moving the source document via 'std::move' (generated by the compiler) ---\n";
		lab3::DocumentManager doc3{ std::move(doc1) };
		doc3.print_info();

		std::cout << "--- The source document after the move operation ---\n";
		doc1.print_info();
	}
	std::cout << "*** End laboratory #3 ***\n\n";

	return 0;
}